SolicitudEmpleados.MVCV3/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SeguridadComun;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.Helpers;
using SolicitudEmpleado.Models;
using SolicitudEmpleado.MVCV3.Componentes.Email;

namespace SolicitudEmpleados.MVCV3.Controllers
{
	/// <summary>
	/// Esta es la clase principal de todo el programa.
	/// </summary>
	public partial class SolicitudesController : BaseController
    {
        #region Procesar Resultados de Consultas a Solicitudes

        private List<int> listaEstado = new List<int>();

        private List<int> listaTipos = new List<int>();

        private IEnumerable<object> getResultado(int jtStartIndex, int jtPageSize, string jtSorting, string searchString, ref int intCantidad, int? empresaID = 0, int? estatusID = 0, int? tipoID = 0, int viewType = 0, int asignadoID = 0, string q = "", int qt = 0)
        {

			var listaTipoSolicitud = new List<int>();
			if (TieneAcceso("SolicitudesPersonal"))
			{
				listaTipoSolicitud.Add(1);
			}
			if (TieneAcceso("SolicitudesCooperativa"))
			{
				listaTipoSolicitud.Add(2);
			}
			if (TieneAcceso("SolicitudesEliminadas"))
			{
				listaTipoSolicitud.Add(10);
			}
			if (TieneAcceso("SolicitudesGenerales"))
			{
				listaTipoSolicitud.Add(11);
			}

			var solicitudes = (
                from obj in unitOfWork.SolicitudesRepository.Get(includeProperties: "TiposSolicitud")
				where listaTipoSolicitud.Contains(obj.TipoSolicitudID)
				select new
                {
                    SolicitudID = obj.SolicitudID,
                    EmpresaID = obj.EmpresaID,
                    TipoSolicitudID = obj.TipoSolicitudID,
                    TipoID = obj.TipoID,
                    EstatusID = obj.EstatusID,
                    FechaSolicitud = obj.FechaSolicitud,
                    CodigoEmpleado = obj.CodigoEmpleado,
                    NombreEmpleado = obj.NombreEmpleado,
                    Direccion = obj.Direccion,
                    TelefonoOficina = obj.TelefonoOficina,
                    Extension = obj.Extension,
                    TelefonoCelular = obj.TelefonoCelular,
                    Email = obj.Email,
                    Posicion = obj.Posicion,
                    Departamento = obj.Departamento,
                    TiempoServicio = obj.TiempoServicio,
                    Cuenta = obj.Cuenta,
                    Sueldo = obj.Sueldo,
                    CreadoPor = obj.CreadoPor,
                    FechaCreacion = obj.FechaCreacion,
                    ModificadoPor = obj.ModificadoPor,
                    FechaModificacion = obj.FechaModificacion,
                    AsignadoA = obj.AsignadoA,
                    NumeroSolicitud = obj.NumeroSolicitud,
                    UsuarioDeRed = obj.UsuarioDeRed,
                    Cedula = obj.Identificacion,
                    AsignadoANombre = obj.AsignadoANombre,
                    Fecha = obj.FechaSolicitud,
                    EmpresaNombre = obj.Empresa.Nombre,
                    Monto = obj.Monto
                });

            if (!String.IsNullOrEmpty(searchString))
            {
                solicitudes = solicitudes.Where(p => p.CodigoEmpleado.ToString().ToUpper().Trim() == searchString.ToUpper() ||
                                                p.Cedula.ToUpper().ToUpper().Trim() == searchString.ToUpper() ||
                                                p.SolicitudID.ToString().ToUpper() == searchString.ToUpper() ||
                                                p.NombreEmpleado.Contains(searchString.ToUpper()));
            } 
     
            if (!String.IsNullOrEmpty(q))
            {
                if (qt == 0)
                {
                    solicitudes = solicitudes.Where(p => p.CodigoEmpleado.ToString() == q);
                }
                if (qt == 1)
                {
                    solicitudes = solicitudes.Where(p => p.Cedula == q);
                }
                if (qt == 2)
                {
                    solicitudes = solicitudes.Where(p => p.SolicitudID.ToString() == q);
                }
                if (qt == 3)
                {
                    solicitudes = solicitudes.Where(p => p.NumeroSolicitud == q);
                }

            }

            if ((estatusID == 0 || estatusID == null) && listaEstado.Count > 0)
            {
                if (viewType == stViewType.Pendientes && (tipoID == null || tipoID == 0) && (empresaID == null || empresaID == 0) && (asignadoID == 0))
                {
                    solicitudes = from p in solicitudes
                                    where p.EstatusID == 1
                                    select p;
                }
                else
                {
                    solicitudes = from p in solicitudes
                                    where listaEstado.Contains(p.EstatusID)
                                    select p;
                }

            }

            if (estatusID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.EstatusID == estatusID
                                select p;

            }

            if ((tipoID == 0 || tipoID == null) && listaTipos.Count > 0)
            {
                solicitudes = from p in solicitudes
                                where listaTipos.Contains(p.TipoID)
                                select p;
            }

            if (tipoID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.TipoID == tipoID
                                select p;
            }
            if (empresaID > 0)
            {
                solicitudes = from p in solicitudes
                                where p.EmpresaID == empresaID
                                select p;
            }
            if (asignadoID > 0)
            {
                solicitudes = solicitudes.Where(p => p.AsignadoA == asignadoID);
            }
      
            if (viewType == stViewType.MisSolicitudes)
            {
                solicitudes = solicitudes.Where(p => p.AsignadoA == currentUser.codigoEmpleado);
            }
          
            if (viewType == stViewType.Pendientes || viewType == stViewType.EnProceso)
            {
                if (viewType == stViewType.Pendientes && asignadoID <= 0)
                {
                    solicitudes = solicitudes.Where(p => p.AsignadoA == null || p.AsignadoA == 0);
                }
            }
			//solicitudes = solicitudes.Where(p => listaTipoSolicitud.Contains(p.TipoSolicitudID));
			intCantidad = solicitudes.Count();
            return solicitudes.OrderBy(s => s.SolicitudID).Skip(jtStartIndex).Take(jtPageSize).ToList();
        }

        #endregion

        #region Llenar los Combo Box y Opciones de Resultados

        [HttpPost]
        public JsonResult GetEstatusOptions()
        {
            try
            {
                var estatus = getListaEstatus().Select(
                    c => new { DisplayText = c.Nombre, Value = c.EstatusID });
                return Json(new { Result = "OK", Options = estatus });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetTiposOptions()
        {
            try
            {
                var tipos = getListaTipo().Select(
                    c => new { DisplayText = c.Nombre, Value = c.TipoID });
                return Json(new { Result = "OK", Options = tipos });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetAsignadoOptions(int id = 0)
        {
            try
            {
                var tipos = getListaAsignado(0, id).Select(
                    c => new { DisplayText = c.AsignadoANombre, Value = c.AsignadoA });
                return Json(new { Result = "OK", Options = tipos });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        private void SetCombox(bool getEstadoEstatus = false)
        {
            bool esSupervisor = true;

            listaEstado = unitOfWork.SolicitudesRepository.GetEstadosDropDown(esSupervisor).ToList();
           
            listaTipos = new List<int>();

			var seguridad = ObtenerSeguridad();

			foreach (var item in seguridad.Modulos)
			{
				if (item.permisoLeer) 
				{
					listaTipos.Add(item.idModulo);
				}
			}
			ViewBag.Supervisor = "true";

            if (!getEstadoEstatus)
            {
                ViewBag.EmpresaID = new SelectList(getListaEmpresa(), "EmpresaID", "Nombre");
                ViewBag.Asignado = new SelectList(getListaAsignado(), "AsignadoA", "AsignadoANombre");
                ViewBag.EstatusID = new SelectList(getListaEstatus(listaEstado.ToArray()), "EstatusID", "Nombre");
                ViewBag.TipoID = new SelectList(getListaTipo(listaTipos.ToArray()), "TipoID", "Nombre");
            }
        }

        #endregion

        #region Lista y Update de Solicitudes JSON

        [HttpPost]
        [OutputCache(Duration = 10, VaryByParam = "*")]
        public JsonResult SolicitudesList(int? EmpresaID = 0, int? EstatusID = 0, int? TipoID = 0, int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = "", string searchString = "", int viewType = 0, int Asignado = 0, string q = "", int qt = 0)
        {
            try
            {
                SetCombox(true);
                //Get data from database
                int solicitudCount = 0;

SolicitudEmpleados.MVCV3/Views/Solicitudes/Crear.cshtml
@model SolicitudEmpleado.Models.EditarSolicitudViewModel

@{
    Layout = "~/Views/Shared/Layouts/_Layout_NotLogged.cshtml";
}

@using SolicitudEmpleado.Helpers

@{
    ViewBag.Title = " Crear Nueva " + ViewBag.TipoSolicitudNombre;
    int lastTipoPropiedadID = 0;
    int nextTipoPropiedadID = 0;
    int indexTipoPropiedadID = 1;
    int columna = 1;
    int fila = 1;
    bool esTabla = false;
    bool esAgregar = false;
    int nextTipoPropiedadID2 = 0;
    int indexTipoPropiedadID2 = 1;
    if (Model.SolicitudEnviada)
    {
        ViewBag.Title = "Solicitud Enviada";
    }
}

<div class="row">
    <div class="col-md-12">
        <form method="post" action="@Request.Url.PathAndQuery" data-is-error="@Model.MostrarSoloErrorPrincipal">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(p => p.solicitud.SolicitudID)
            @Html.HiddenFor(p => p.solicitud.TipoSolicitudID)
            @Html.HiddenFor(p => p.solicitud.TipoID)
            @Html.HiddenFor(p => p.solicitud.TipoIdentificacionID)

            <h3 class="titulo">@ViewBag.Title</h3>
      
            <div class="row">
                @if (Model.SolicitudEnviada)
                {
                    <p class="bg-primary" style="padding: 15px; font-style: italic;">Datos Enviados Correctamente, por favor contactarse con el encargado y informar que ya lleno la solicitud. Numero de Solicitud es: @Model.solicitud.SolicitudID.ToString(). Muchas Gracias!</p>
                    <div class="col-sm-12 col-md-12">
                        <div class="text-center">
                            <a class="btn btn-primary" href="~/"><i class="icon-home"></i>&nbsp;Inicio</a>
                            <a class="btn btn-primary" href="~/Solicitudes/Crear/1"><i class="icon-off"></i>&nbsp;Nueva Activacion</a>
                            <a class="btn btn-primary" href="~/Solicitudes/Crear/2"><i class="icon-exchange"></i>&nbsp;Nuevo Cambio de Plan</a>
                            <a class="btn btn-primary" href="~/Solicitudes/Crear/3"><i class="icon-plus-sign-alt"></i>&nbsp;Nuevo Adicion de Linea</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <ul class="breadcrumbs">
                            <li class="first"><a href="~/" class="icon-home"></a></li>
                            @for (int i = 0; i < Model.Procesar.Count; i++)
                            {
                                if (nextTipoPropiedadID2 == 0 || nextTipoPropiedadID2 != Model.Procesar[i].TipoPropiedadID)
                                {
                                    <li class="item-li li-@indexTipoPropiedadID2 @(indexTipoPropiedadID2==1 ? "active" : "")" data-index="@indexTipoPropiedadID2"><a href="#" class="a-@indexTipoPropiedadID2">@Model.Procesar[i].TipoPropiedadNombre</a></li>
                                    nextTipoPropiedadID2 = Model.Procesar[i].TipoPropiedadID;
                                    indexTipoPropiedadID2++;
                                }
                            }
                        </ul>
                    </div>
                       
                        @Html.ValidationSummary(Model.MostrarSoloErrorPrincipal, "", new { @class = "alert alert-danger" })
                        <div class="panels">
                            @for (int i = 0; i < Model.Procesar.Count; i++)
                            {
                                string idcontrol = "Procesar_" + i.ToString() + "__Valor";
                                if (nextTipoPropiedadID == 0 || nextTipoPropiedadID != Model.Procesar[i].TipoPropiedadID)
                                {
                                    if (esTabla)
                                    {
                                        var botonAgregar = (esAgregar ? "<button type='button' class='add-to-table btn btn-primary pull-right' data-tr='tr-" + lastTipoPropiedadID.ToString() + "'><i class='icon-plus'></i></button><button type='button' class='rem-to-table btn btn-primary pull-right' data-tr='tr-" + lastTipoPropiedadID.ToString() + "'><i class='icon-minus'></i></button>" : "");
                                        @Html.Raw("</tbody></table>" + botonAgregar + "</div>")
                                        esTabla = false;
                                        esAgregar = false;
                                    }
                                    lastTipoPropiedadID = Model.Procesar[i].TipoPropiedadID;
                                    if (nextTipoPropiedadID == 0)
                                    {
                                        @Html.Raw("<div class='active panel-" + @indexTipoPropiedadID + "' data-index='" + @indexTipoPropiedadID + "'>")
                                    }
                                    else
                                    {
                                        @Html.Raw("</div><div class='panel-" + @indexTipoPropiedadID + "' data-index='" + @indexTipoPropiedadID + "'>")
                                    }
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <h5>
                                            @Model.Procesar[i].TipoPropiedadNombre
                                        </h5>
                                        <hr />
                                    </div>if (Model.Procesar[i].Columnas.HasValue)
                                    {
                                        esTabla = true;
                                        esAgregar = Model.Procesar[i].Agregar;
                                        @Html.Raw("<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'><table class='table table-bordered table-condensed table-striped ta-" + Model.Procesar[i].TipoPropiedadID.ToString() + "' data-columnas='" + Model.Procesar[i].Columnas.ToString() + "'><thead><tr>")
                                    }
                                    nextTipoPropiedadID = Model.Procesar[i].TipoPropiedadID;
                                    indexTipoPropiedadID++;
                                    columna = 1;
                                    fila = 1;
                                }

                                if (!Model.Procesar[i].Columnas.HasValue)
                                {
                                    <div style="display:none;">
                                        @Html.HiddenFor(p => p.Procesar[i].Nombre)
                                        @Html.HiddenFor(p => p.Procesar[i].PropiedadID)
                                        @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadNombre)
                                        @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadID)
                                    </div>
                                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label class="control-label" for="@idcontrol">
                                                @Html.DisplayFor(model => model.Procesar[i].Nombre)
                                            </label>
                                            <div>
                                                @Html.EditorForPropiedad(Model.Procesar[i], "Procesar[" + i.ToString() + "]")
                                                @Html.ValidationMessageForPropiedad("Procesar[" + i.ToString() + "]")
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    if (fila == 1)
                                    {
                                        <td>
                                            @Html.HiddenFor(p => p.Procesar[i].Nombre)
                                            @Html.HiddenFor(p => p.Procesar[i].PropiedadID)
                                            @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadNombre)
                                            @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadID)
                                            <label class="control-label" for="@idcontrol">
                                                @Html.DisplayFor(model => model.Procesar[i].Nombre)
                                            </label>
                                        </td>
                                        if (columna == Model.Procesar[i].Columnas)
                                        {
                                            @Html.Raw("</tr></thead><tbody>")
                                        }
                                    }
                                    else
                                    {
                                        if (columna == 1)
                                        {
                                            @Html.Raw("<tr class='tr-" + Model.Procesar[i].TipoPropiedadID.ToString() + " id-" + Model.Procesar[i].PropiedadID.ToString() + "' >")
                                        }
                                        <td>
                                            @Html.HiddenFor(p => p.Procesar[i].Nombre)
                                            @Html.HiddenFor(p => p.Procesar[i].PropiedadID)
                                            @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadNombre)
                                            @Html.HiddenFor(p => p.Procesar[i].TipoPropiedadID)
                                            @Html.EditorForPropiedad(Model.Procesar[i], "Procesar[" + i.ToString() + "]")
                                            @Html.ValidationMessageForPropiedad("Procesar[" + i.ToString() + "]")
                                        </td>
                                        if (columna == Model.Procesar[i].Columnas)
                                        {
                                            @Html.Raw("</tr>")
                                        }
                                    }

                                    if (columna == Model.Procesar[i].Columnas)
                                    {
                                        fila++;
                                        columna = 0;
                                    }
                                    columna++;
                                }
                            }
                            @if (esTabla)
                            {
                                var botonAgregar = (esAgregar ? "<button type='button' class='add-to-table btn btn-primary pull-right' data-tr='tr-" + lastTipoPropiedadID.ToString() + "'><i class='icon-plus'></i></button><button type='button' class='rem-to-table btn btn-primary pull-right' data-tr='tr-" + lastTipoPropiedadID.ToString() + "'><i class='icon-minus'></i></button>" : "");
                                @Html.Raw("</tbody></table>"+ botonAgregar + "</div>")
                                esTabla = false;
                                esAgregar = false;
                            }
                            @Html.Raw("</div>")
                        </div>
                        <div class="clearfix" style="height: 10px;"></div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <hr />
                            <button type="button" value="back" class="hide back btn btn-primary pull-left"><i class="icon-undo"></i>&nbsp;Atras </button>
                            <button type="button" value="next" class="next btn btn-primary pull-right"><i class="icon-chevron-right"></i>&nbsp;Siguiente </button>
                            <button type="submit" value="submit" class="hide submit-form btn btn-primary pull-right"> Finalizar </button>
                        </div>
                        <div style="display:none;">
                            <input id="index-procesar" name="index-procesar" class="index-procesar" type="hidden" value="@Model.Procesar.Count">
                        </div>
                        }
                    </div>
        </form>
    </div>
</div>

@section scripts{

    <style>
        .panels > div {
            display: none;
        }

        .panels .active {
            display: inherit !important;
        }

        .add-to-table {
            margin-left: 15px;
        }
    </style>

    <!-- Validacion de MVC -->

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <!-- Validacion de MVC END -->

    <script src="~/Scripts/number_format.js"></script>
    <script src="~/Scripts/Solicitudes/Crear.js"></script>
    <link href="~/Content/breadcrumbs.css" rel="stylesheet" />
    <script src="~/Scripts/Solicitudes/breadcrumbs.js"></script>

}

SolicitudEmpleados.MVCV3/Views/Solicitudes/Details.cshtml
@model SolicitudEmpleado.Models.DetalleSolicitudViewModel
@using SolicitudEmpleado.Helpers

@{
    ViewBag.Title = "Detalle " + @Model.solicitud.TiposSolicitud.Nombre + " " + @Model.solicitud.Tipos.Nombre;
    int nextTipoPropiedadID = 0;
	int indexTipoPropiedadID = 1;
	int columna = 1;
	int fila = 1;
	bool esTabla = false;
}

<div class="row">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <h3 class="titulo pull-left">@ViewBag.Title</h3>
        <h3 class="pull-right">#@Model.solicitud.SolicitudID</h3>
    </div>

	<div class="panels">
		@foreach (var item in Model.Procesar)
		{
			if (nextTipoPropiedadID == 0 || nextTipoPropiedadID != item.TipoPropiedadID)
			{
				if (esTabla)
				{
					@Html.Raw("</tbody></table></div>")
					esTabla = false;
				}
				if (nextTipoPropiedadID == 0) 
				{
					@Html.Raw("<div class='active panel-" + @indexTipoPropiedadID + "' data-index='" + @indexTipoPropiedadID + "'>")
				}
				else
				{
					@Html.Raw("</div><div class='panel-" + @indexTipoPropiedadID + "' data-index='" + @indexTipoPropiedadID + "'>")
				}
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<h5>
						 @item.TipoPropiedadNombre
					</h5>
					<hr />
				</div>
				if (@item.Columnas.HasValue)
				{
					esTabla = true;
					@Html.Raw("<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'><table class='table table-bordered table-condensed table-striped'><thead><tr>")
				}
				nextTipoPropiedadID = @item.TipoPropiedadID;
				indexTipoPropiedadID++;
				columna = 1;
				fila = 1;
			}				
			
			if (!@item.Columnas.HasValue)
			{
				<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
						<label class="control-label">
							@Html.DisplayFor(modelItem => item.Nombre)
						</label>
						<div>
							@Html.DisplayForPropiedad(item)  &nbsp;
						</div>
					</div>
				</div>
			}
			else
			{
				if (fila == 1)
				{
					<td>
						<label class="control-label">
							@Html.DisplayFor(modelItem => item.Nombre)
						</label>
					</td>
					if (columna == item.Columnas)
					{
						@Html.Raw("</tr></thead><tbody>")
					}
				}
				else
				{
					if (columna == 1)
					{
						@Html.Raw("<tr>")
					}
					<td>
						@Html.DisplayForPropiedad(item)  &nbsp;
					</td>
					if (columna == item.Columnas)
					{
						@Html.Raw("</tr>")
					}
				}

				if (columna == item.Columnas)
				{
					fila++;
					columna = 0;
				}
				columna++;
			}
		}
		@if (esTabla)
		{
			@Html.Raw("</tbody></table></div>")
			esTabla = false;
		}
		@Html.Raw("</div>")
	</div>

    <div class="fullrow visible-print">

        <div class="container">

            <div class="row-fluid" style="padding-top:50px">
             
            </div>

        </div>

    </div>
    <div class="no-print col-lg-12 col-md-12 col-sm-12 col-xs-12">
        @Html.Action("_Comentarios", "Comentarios", new { SolicitudID = Model.solicitud.SolicitudID })
        <div class="form-actions">
            <button id="btnImprimir" type="submit" value="Imprimir" class="btn btn-primary"> Imprimir </button>
        </div>
    </div>

</div>


@section scripts{

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <script>

        $(function () {
            $('#btnImprimir').click(btnImprimir);
        });

        function btnImprimir() {
            window.print();
        }

    </script>
    <script src="~/Scripts/Comentarios/AgregarComentario.js"></script>
   
}

SolicitudEmpleados.MVCV3/Views/Solicitudes/Index.cshtml
@model IEnumerable<dynamic>
@using SolicitudEmpleado.Helpers

<div class="row">
    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>
        @Html.Partial("_MensajeError")
        <div style="height: 85px;">
            <form class="table-update-trigger">

                <div class="col-sm-4 col-md-4" style="padding-left: 0px;">
                    <label class="title">Tipo</label>
                    <div class="">
                        @Html.DropDownList("TipoID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="col-sm-4 col-md-4">
                    <label class="title">Estado</label>
                    <div class="">
                        @Html.DropDownList("EstatusID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                @if (ViewBag.ViewType != @stViewType.MisSolicitudes)
                {
                    <div class="col-sm-4 col-md-4" style="padding-right:0px;">
                        <label class="title">Asignado A</label>
                        <div class="">
                            @Html.DropDownList("Asignado", null, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>}

            </form>

        </div>


        <div id="divContenedorSolicitudes"
             data-url="@Url.Action("","Solicitudes")"
             data-viewtype="@ViewBag.ViewType"
             data-supervisor="@ViewBag.Supervisor"
			 data-app-name="@System.Web.Configuration.WebConfigurationManager.AppSettings["Seguridad.App.Nombre"]">
        </div>
    </div>
</div>


<br />

@section scripts{

    @{
        //Para Usar un Tema de JQuery UI

        //var jQueryStyle = "flick/jquery-ui.flick.min.css";
        //var jQueryStyle = "smoothness/jquery-ui.smoothness.min.css";
        var jQueryStyle = "custom-theme/jquery-ui-1.10.3.custom.css";
        if (!string.IsNullOrEmpty(Request["jQueryStyle"]))
        {
            jQueryStyle = Request["jQueryStyle"];
        }

        //var jTableStyle = "lightcolor/gray/jtable.css";
        var jTableStyle = "jqueryui/jtable_jqueryui.css";
        //var jTableStyle = "metro/lightgray/jtable.min.css";
        if (!string.IsNullOrEmpty(Request["jTableStyle"]))
        {
            jTableStyle = Request["jTableStyle"];
        }

    }

    <!-- JTable Control BEGIN -->
    <link href="@Url.Content("~/Content/themes/" + jQueryStyle)" rel="stylesheet" type="text/css" /> @*//Para Usar un Tema de JQuery UI*@
    <link href="@Url.Content("~/Scripts/jtable/themes/" + jTableStyle)" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/jquery.jtable.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jtable/localization/jquery.jtable.es.js")"></script>
    <!-- JTable Control END -->
    <!-- Mi Codigo -->
    <script src="~/Scripts/number_format.js"></script>
    <script src="~/Scripts/Solicitudes/Index.js"></script>

}