SolicitudEmpleados.MVCV3/Controllers/TransaccionesDisponiblidadsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolicitudEmpleado.Helpers;
using SolicitudEmpleado.Data;
using SolicitudEmpleado.Models;

namespace SolicitudEmpleados.MVCV3.Controllers
{
    public class TransaccionesDisponiblidadsController : BaseController
    {
        private dbSolicitudesContext db = new dbSolicitudesContext();

        // GET: TransaccionesDisponiblidads
        public ActionResult Index(int id = 0)
        {

            ViewBag.ListaReferencia = new SelectList(db.ReferenciasEikons, "ReferenciaEikonId", "Nombre");
            var modelo = new ListadoTransaccionesViewModel();
            modelo.Listado = db.TransaccionesDisponiblidades.Include(t => t.Propiedad).Include(t => t.ReferenciaEikon);

            if (id > 0)
            {
                modelo.Listado = modelo.Listado.Where(p => p.ReferenciaEikonId == id); ;
                modelo.ReferenciEikonId = id;
                return View(modelo);
            }

            return View(modelo);

        }

        // GET: TransaccionesDisponiblidads/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransaccionesDisponiblidad transaccionesDisponiblidad = db.TransaccionesDisponiblidades.Find(id);
            if (transaccionesDisponiblidad == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
                    return PartialView(transaccionesDisponiblidad);

            return View(transaccionesDisponiblidad);
        }

        // GET: TransaccionesDisponiblidads/Create
        public ActionResult Create()
        {
            ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarDeducciones || p.TipoPropiedadID == PropiedadesTipos.EditarIngresos).OrderBy(p => p.Nombre), "PropiedadID", "Nombre");
            ViewBag.ReferenciaEikonId = new SelectList(db.ReferenciasEikons, "ReferenciaEikonId", "Nombre");
            if (Request.IsAjaxRequest())
                    return PartialView();

            return View();
        }

        // POST: TransaccionesDisponiblidads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TransaccionId,ReferenciaEikonId,Codigo,PropiedadID,Nombre")] TransaccionesDisponiblidad transaccionesDisponiblidad)
        {
            if (ModelState.IsValid)
            {
                transaccionesDisponiblidad.AuditoriaCrear(currentUser.codigoEmpleado);
                db.TransaccionesDisponiblidades.Add(transaccionesDisponiblidad);
                db.SaveChanges();
                if (Request.IsAjaxRequest())
                    return PartialView(transaccionesDisponiblidad);

                return RedirectToAction("Index");
            }

            ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarDeducciones || p.TipoPropiedadID == PropiedadesTipos.EditarIngresos).OrderBy(p => p.Nombre), "PropiedadID", "Nombre", transaccionesDisponiblidad.PropiedadID);
            ViewBag.ReferenciaEikonId = new SelectList(db.ReferenciasEikons, "ReferenciaEikonId", "Nombre", transaccionesDisponiblidad.ReferenciaEikonId);
            if (Request.IsAjaxRequest())
                return PartialView(transaccionesDisponiblidad);

            return View(transaccionesDisponiblidad);
        }

        // GET: TransaccionesDisponiblidads/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransaccionesDisponiblidad transaccionesDisponiblidad = db.TransaccionesDisponiblidades.Find(id);
            if (transaccionesDisponiblidad == null)
            {
                return HttpNotFound();
            }
            ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarDeducciones || p.TipoPropiedadID == PropiedadesTipos.EditarIngresos).OrderBy(p => p.Nombre), "PropiedadID", "Nombre", transaccionesDisponiblidad.PropiedadID);
            ViewBag.ReferenciaEikonId = new SelectList(db.ReferenciasEikons, "ReferenciaEikonId", "Nombre", transaccionesDisponiblidad.ReferenciaEikonId);
            if (Request.IsAjaxRequest())
                return PartialView(transaccionesDisponiblidad);

            return View(transaccionesDisponiblidad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TransaccionId,ReferenciaEikonId,Codigo,PropiedadID,Nombre")] TransaccionesDisponiblidad transaccionesDisponiblidad)
        {
            if (ModelState.IsValid)
            {
                transaccionesDisponiblidad.AuditoriaEditar(currentUser.codigoEmpleado);
                db.Entry(transaccionesDisponiblidad).State = EntityState.Modified;
                db.SaveChanges();
                if (Request.IsAjaxRequest())
                    return PartialView();
                return RedirectToAction("Index");
            }
            ViewBag.PropiedadID = new SelectList(db.Propiedades.Where(p => p.TipoPropiedadID == PropiedadesTipos.EditarDeducciones || p.TipoPropiedadID == PropiedadesTipos.EditarIngresos).OrderBy(p => p.Nombre), "PropiedadID", "Nombre", transaccionesDisponiblidad.PropiedadID);
            ViewBag.ReferenciaEikonId = new SelectList(db.ReferenciasEikons, "ReferenciaEikonId", "Nombre", transaccionesDisponiblidad.ReferenciaEikonId);
            if (Request.IsAjaxRequest())
                    return PartialView(transaccionesDisponiblidad);

            return View(transaccionesDisponiblidad);
        }

        // GET: TransaccionesDisponiblidads/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TransaccionesDisponiblidad transaccionesDisponiblidad = db.TransaccionesDisponiblidades.Find(id);
            if (transaccionesDisponiblidad == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
                return PartialView(transaccionesDisponiblidad);

            return View(transaccionesDisponiblidad);
        }

        // POST: TransaccionesDisponiblidads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TransaccionesDisponiblidad transaccionesDisponiblidad = db.TransaccionesDisponiblidades.Find(id);
            db.TransaccionesDisponiblidades.Remove(transaccionesDisponiblidad);
            db.SaveChanges();
            if (Request.IsAjaxRequest())
                return PartialView();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SolicitudEmpleados.MVCV3/Views/TransaccionesDisponiblidads/Create.cshtml
@model SolicitudEmpleado.Data.TransaccionesDisponiblidad

@{
    ViewBag.Title = "Nuevo Transacciones Disponiblidad";
}

<div class="row">
    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

                <div class="form-group">
                    <label class="control-label col-md-2" for="ReferenciaEikonId">Eikon Id</label>
                    <div class="col-md-10">
                        @Html.DropDownList("ReferenciaEikonId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ReferenciaEikonId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PropiedadID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PropiedadID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropiedadID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

@if (Request.IsAjaxRequest())
{
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
}
else
{
    @section scripts {
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    }
}

SolicitudEmpleados.MVCV3/Views/TransaccionesDisponiblidads/Delete.cshtml
@model SolicitudEmpleado.Data.TransaccionesDisponiblidad

@{
    ViewBag.Title = "Eliminar Transacciones Disponiblidad";
}

<div class="row">
    <div class="col-md-12">

        <h3 class="titulo">@ViewBag.Title</h3>

        <h5>Esta seguro que desea eliminar este registro?</h5> @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

        <dl class="dl-horizontal">
            <dt>
                @Html.LabelFor(model => model.Propiedad, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Propiedad.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.ReferenciaEikon, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReferenciaEikon.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Codigo)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions">
                <input type="submit" value="Eliminar" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

SolicitudEmpleados.MVCV3/Views/TransaccionesDisponiblidads/Details.cshtml
@model SolicitudEmpleado.Data.TransaccionesDisponiblidad

@{
    ViewBag.Title = "Detalles Transacciones Disponiblidad";
}

<div class="row">

    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>


        <dl class="dl-horizontal">
            <dt>
                @Html.LabelFor(model => model.Propiedad, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Propiedad.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.ReferenciaEikon, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ReferenciaEikon.Nombre)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Codigo)
            </dd>

            <dt>
                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nombre)
            </dd>

        </dl>
    </div>

</div>

SolicitudEmpleados.MVCV3/Views/TransaccionesDisponiblidads/Edit.cshtml
@model SolicitudEmpleado.Data.TransaccionesDisponiblidad

@{
    ViewBag.Title = "Editar Transacciones Disponiblidad";
}

<div class="row">
    <div class="col-md-12">


        <h3 class="titulo">@ViewBag.Title</h3>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.TransaccionId)
                @Html.HiddenFor(model => model.CreadoPor)
                @Html.HiddenFor(model => model.FechaCreacion)
                <div class="form-group">
                    <label class="control-label col-md-2" for="ReferenciaEikonId">Eikon Id</label>
                    <div class="col-md-10">
                        @Html.DropDownList("ReferenciaEikonId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ReferenciaEikonId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PropiedadID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PropiedadID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PropiedadID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-actions">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
        }
    </div>
</div>

@if (Request.IsAjaxRequest())
{
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
}
else
{
    @section scripts {
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    }
}

SolicitudEmpleados.MVCV3/Views/TransaccionesDisponiblidads/Index.cshtml
@model SolicitudEmpleado.Models.ListadoTransaccionesViewModel

@{
    ViewBag.Title = "Transacciones Disponiblidades";
}
<div class="row">
    <div class="col-md-12">
        <h3 class="titulo">@ViewBag.Title</h3>

        <div class="row">
            <div class="col-md-3" style="z-index: 1">

                @Html.DropDownListFor(model => model.ReferenciEikonId, ViewBag.ListaReferencia as SelectList, new { @class = "form-control myselect2" })

            </div>
        </div>
      

        <table class="display table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().ReferenciaEikon.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Propiedad.Nombre)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Codigo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Listado.FirstOrDefault().Nombre)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Listado) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.ReferenciaEikon.Nombre)
            </td>
            <td>
                @if (item.Propiedad != null)
            {
            @Html.DisplayFor(modelItem => item.Propiedad.Nombre)
            }
            else
            {
            <span>N/A</span>
            }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                        Accion
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#" onclick="cargarModal('@Url.Action("Details", "TransaccionesDisponiblidads", new { id=item.TransaccionId })')">Detalle</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#" onclick="cargarModal('@Url.Action("Edit", "TransaccionesDisponiblidads", new { id=item.TransaccionId })')">Editar</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#" onclick="cargarModal('@Url.Action("Delete", "TransaccionesDisponiblidads", new { id=item.TransaccionId })')">Eliminar</a>
                        </li>
                    </ul>
                </div>
            </td>
        </tr>
}
            </tbody>
        </table>

        <div class="form-actions">
            <a href="#" class="btn btn-primary" onclick="cargarModal('@Url.Action("Create", "TransaccionesDisponiblidads")')">Crear Nuevo Transacciones Disponiblidad</a>
        </div>
    </div>
</div>

@section scripts{

    @*Datatable BEING*@
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.jqueryui.min.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
    @*Datatable END*@

    <!-- Mi Codigo Data Table -->
    <script src="~/Scripts/myCodeDataTable.js"></script>
    
    <script>

        $(document).ready(function () {

            var nombreDelBoton = "#ReferenciEikonId";

            $(nombreDelBoton).change(function () {
                var selectedValue = $('#ReferenciEikonId').val();
                var div = document.getElementById(nombreDelBoton.replace('#', ''));
                var divRoot = document.getElementsByTagName("body")[0].getAttribute('data-root');
                var url = divRoot + 'TransaccionesDisponiblidads/Index/' + selectedValue;
                Redirect(url);

            });

        });


    </script>

}